# fly.toml app configuration file generated for chatappwithsocketio-server on 2024-02-09T14:45:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatappwithsocketio-server'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[services.ports.http_options.response.headers]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "*"
  Access-Control-Allow-Headers = "*"
