# fly.toml app configuration file generated for chatappwithsocketio-server on 2024-01-16T17:40:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chatappwithsocketio-server"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[checks]
  [checks.http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/path/to/status"
    port = 3000
    timeout = "10s"
    type = "http"
    [checks.name_of_your_http_check.headers]
      Content-Type = "application/json"
      Authorization = "super-secret"

